# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87837ce63d313057ab11e9ab0d982ac83dc8e33894afaa74a0e52da7b52118d9b2719791351c383b0fbd3f196cd18b8fa1ccc2535115ea32e5f4facd349db9fa

test:
  secret_key_base: ab5c41508513f60dfdeed801837a67a222882b641a5aecfc18dad853ec8ec6ddcecce35e86168b12cdb1c7800838f62a7e0f43834f32219ae5d74aa9f44493c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
